Add SelectionOptions type and refactor GetThermostat to use them
rspier/go-ecobee pull request #15
Opened 2024-04-21 14:18 UTC by cvvs

I wanted to be able to configure GetThemostat selection data, and you have a TODO to allow for this, so I created a SelectionOption type which can be passed into GetThermostat to set specific selection options when making a request.

I modified the GetThermostat to take the options as a variadic parameter, so the change should be backwards compatible.

Originally, the option funcs were all `With<SettingName>` but that seemed redundant, so removed the With.

I can undo the formatting changes made by gofmt if you prefer.

2024-05-13 03:50 UTC, rspier requested changes
Sorry for the delayed review, April and early May were something special...
 
Anyway, thank  you for the PR.  A few very minor tweaks if you don't mind...

> Originally, the option funcs were all With<SettingName> but that seemed redundant, so removed the With.

I agree the `With` is providing much value, but the option func pattern generally uses it, so in the name of consistency, maybe add them back?  (Or you could probably convince me I'm being silly about that.)

> I can undo the formatting changes made by gofmt if you prefer.

Yes please.  I'm not opposed to the changes, but let's make them outside the scope of this PR.  Also, what version of gofmt are you using?  1.22 isn't making those changes for me.

2024-05-13 03:50 UTC, rspier commented on ecobee/functions.go
> +	for _, optfn := range opts {
just `o` is ok here.  Or `opt` if you'd prefer.  The scope is one line, there won't be any confusion.

I try to follow the [Google Go style guide](https://google.github.io/styleguide/go/)

2024-06-24 22:56 UTC, cvvs commented
I'll try to get the requested changes done as soon as I get some spare dev time.

2024-06-29 23:02 UTC, merged

2024-06-29 23:03 UTC, rspier commented
Merged, thank you!

In hindsight, I wonder if we should have just done WithSelection(*Selection)? as a GetThermostatOption func?

2024-06-30 00:00 UTC, cvvs commented
Funny you should say that.   I was working on a mock http client this week, and after writing way too many options, and ended up doing something similar with requests. Given that, it's probably the best solution, and had I done this this weekend, that's probably what I would have done.

2024-06-30 04:15 UTC, rspier commented
It's not too late to change our mind and switch the interface.  

I figure we can retain a default Selection for the common case, but anyone who wants something special can specify all the fields they care about.